# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [3]:
s.split(" ")

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [6]:
planet = "Earth"
diameter = 12742

In [7]:
"The diameter of {} is {} kilometers".format(planet,diameter)
'The diameter of Earth is 12742 kilometers'

'The diameter of Earth is 12742 kilometers'

## 3. In this nest dictionary grab the word "hello"

In [8]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [12]:
sh=d["k1"][3]["tricky"][3]["target"][3]
print(sh)


hello


# Numpy

In [13]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [19]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [21]:
even=np.arange(20,35,2)
print(even)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
shape =  np.arange(0, 9).reshape(3,3)
print(shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [23]:
a = np.array([1, 2,3])
b = np.array([4,5, 6])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [28]:
import pandas as pd


In [29]:
A = np.random.randint(10, size=(3,2))
df = pd.DataFrame(A,columns=['id1', 'id2'])
df

id1  id2
0    9    3
1    8    9
2    3    2

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
date = pd.date_range(start ='1-1-2023', 
         end ='10-02-2023')
  
for val in date:
    print(val)

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [31]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [32]:
ls = pd.DataFrame(lists, columns =['mark1',"mark2","mark3"]) 
ls


mark1 mark2  mark3
0      1   aaa     22
1      2   bbb     25
2      3   ccc     24